TEMPLATE = app
CONFIG += console
CONFIG -= app_bundle
CONFIG -= qt

SOURCES += main.cpp \
    ../../../core/Types.cpp \
    ../../../core/SPIDevice.cpp \
    ../../../core/SPIBus.cpp \
    ../../../core/SoftwareSerial.cpp \
    ../../../core/Socket.cpp \
    ../../../core/SerialDevice.cpp \
    ../../../core/Module.cpp \
    ../../../core/Mainboard.cpp \
    ../../../core/List.cpp \
    ../../../core/Interfaces.cpp \
    ../../../core/I2CDevice.cpp \
    ../../../core/I2CBus.cpp \
    ../../../core/DaisyLinkCommandBus.cpp \
    ../../../core/DaisyLink.cpp \
    ../../../modules/ghi/Accelerometer/Accelerometer.cpp \
    ../../../modules/ghi/AccelG248/AccelG248.cpp \
    ../../../modules/ghi/ALFATLink/ALFATLink.cpp \
    ../../../modules/ghi/Barometer/Barometer.cpp \
    ../../../modules/ghi/Breakout/Breakout.cpp \
    ../../../modules/ghi/Button/Button.cpp \
    ../../../modules/ghi/CharDisplay/CharDisplay.cpp \
    ../../../modules/ghi/ColorSense/ColorSense.cpp \
    ../../../modules/ghi/Compass/Compass.cpp \
    ../../../modules/ghi/CurrentACS712/CurrentACS712.cpp \
    ../../../modules/ghi/DisplayN18/DisplayN18.cpp \
    ../../../modules/ghi/DistanceUS3/DistanceUS3.cpp \
    ../../../modules/ghi/Extender/Extender.cpp \
    ../../../modules/ghi/FEZTive/FEZtive.cpp \
    ../../../modules/ghi/FLASH/FLASH.cpp \
    ../../../modules/ghi/FMRadio/FMRadio.cpp \
    ../../../modules/ghi/GasSense/GasSense.cpp \
    ../../../modules/ghi/Gyroscope/Gyroscope.cpp \
    ../../../modules/ghi/IO60P16/IO60P16.cpp \
    ../../../modules/ghi/Joystick/Joystick.cpp \
    ../../../modules/ghi/KeypadKP16/KeypadKP16.cpp \
    ../../../modules/ghi/LED7C/LED7C.cpp \
    ../../../modules/ghi/LED7R/LED7R.cpp \
    ../../../modules/ghi/LEDMatrix/LEDMatrix.cpp \
    ../../../modules/ghi/LEDStrip/LEDStrip.cpp \
    ../../../modules/ghi/LightSensor/LightSensor.cpp \
    ../../../modules/ghi/Load/Load.cpp \
    ../../../modules/ghi/MaxO/MaxO.cpp \
    ../../../modules/ghi/Moisture/Moisture.cpp \
    ../../../modules/ghi/MotionSensor/MotionSensor.cpp \
    ../../../modules/ghi/MotorDriverL298/MotorDriverL298.cpp \
    ../../../modules/ghi/MultiColorLED/MultiColorLED.cpp \
    ../../../modules/ghi/Potentiometer/Potentiometer.cpp \
    ../../../modules/ghi/PulseCount/PulseCount.cpp \
    ../../../modules/ghi/RelayX1/RelayX1.cpp \
    ../../../modules/ghi/RelayX16/RelayX16.cpp \
    ../../../modules/ghi/RotaryH1/RotaryH1.cpp \
    ../../../modules/ghi/RS232/RS232.cpp \
    ../../../modules/ghi/TemperatureHumidity/TemperatureHumidity.cpp \
    ../../../modules/ghi/Thermocouple/Thermocouple.cpp \
    ../../../modules/ghi/TouchC8/TouchC8.cpp \
    ../../../modules/ghi/TouchL12/TouchL12.cpp \
    ../../../modules/ghi/Tunes/Tunes.cpp \
    ../../../modules/ghi/USBSerial/USBSerial.cpp \
    ../../../modules/ghi/WiFiRN171/WiFiRN171.cpp \
    ../../../mainboards/ghi/FEZLynxS4/s_System.cpp \
    ../../../mainboards/ghi/FEZLynxS4/s_SPIBus.cpp \
    ../../../mainboards/ghi/FEZLynxS4/s_SoftwareI2CBus.cpp \
    ../../../mainboards/ghi/FEZLynxS4/s_SerialDevice.cpp \
    ../../../mainboards/ghi/FEZLynxS4/s_I2CBus.cpp \
    ../../../mainboards/ghi/FEZLynxS4/FTDI_Device.cpp \
    ../../../mainboards/ghi/FEZLynxS4/FEZLynxS4.cpp \
    ../../../modules/seeed/TemperatureHumidity/TemperatureHumidity.cpp \
    ../../../modules/seeed/Gyroscope/Gyroscope.cpp \
    ../../../modules/seeed/Compass/Compass.cpp \
    ../../../modules/seeed/Barometer/Barometer.cpp \
    ../../../modules/seeed/Accelerometer/Accelerometer.cpp

HEADERS += \
    ../../../core/Types.hpp \
    ../../../core/System_proxy.hpp \
    ../../../core/System.hpp \
    ../../../core/SPIDevice.hpp \
    ../../../core/SPIBus.hpp \
    ../../../core/SoftwareSerial.hpp \
    ../../../core/Socket.hpp \
    ../../../core/SerialDevice.hpp \
    ../../../core/Module.hpp \
    ../../../core/Mainboard.hpp \
    ../../../core/List.hpp \
    ../../../core/Interfaces_proxy.hpp \
    ../../../core/Interfaces.hpp \
    ../../../core/I2CDevice.hpp \
    ../../../core/I2CBus.hpp \
    ../../../core/Gadgeteering.h \
    ../../../core/DaisyLinkCommandBus.hpp \
    ../../../core/DaisyLink.hpp \
    ../../../modules/ghi/Accelerometer/Accelerometer.h \
    ../../../modules/ghi/AccelG248/AccelG248.h \
    ../../../modules/ghi/ALFATLink/ALFATLink.h \
    ../../../modules/ghi/Barometer/Barometer.h \
    ../../../modules/ghi/Breakout/Breakout.h \
    ../../../modules/ghi/Button/Button.h \
    ../../../modules/ghi/CharDisplay/CharDisplay.h \
    ../../../modules/ghi/ColorSense/ColorSense.h \
    ../../../modules/ghi/Compass/Compass.h \
    ../../../modules/ghi/CurrentACS712/CurrentACS712.h \
    ../../../modules/ghi/DisplayN18/DisplayN18.h \
    ../../../modules/ghi/DistanceUS3/DistanceUS3.h \
    ../../../modules/ghi/Extender/Extender.h \
    ../../../modules/ghi/FEZTive/FEZtive.h \
    ../../../modules/ghi/FLASH/FLASH.h \
    ../../../modules/ghi/FMRadio/FMRadio.h \
    ../../../modules/ghi/GasSense/GasSense.h \
    ../../../modules/ghi/Gyroscope/Gyroscope.hpp \
    ../../../modules/ghi/IO60P16/IO60P16.h \
    ../../../modules/ghi/Joystick/Joystick.h \
    ../../../modules/ghi/KeypadKP16/KeypadKP16.h \
    ../../../modules/ghi/LED7C/LED7C.h \
    ../../../modules/ghi/LED7R/LED7R.h \
    ../../../modules/ghi/LEDMatrix/LEDMatrix.h \
    ../../../modules/ghi/LEDStrip/LEDStrip.h \
    ../../../modules/ghi/LightSensor/LightSensor.h \
    ../../../modules/ghi/Load/Load.h \
    ../../../modules/ghi/MaxO/MaxO.h \
    ../../../modules/ghi/Moisture/Moisture.h \
    ../../../modules/ghi/MotionSensor/MotionSensor.h \
    ../../../modules/ghi/MotorDriverL298/MotorDriverL298.h \
    ../../../modules/ghi/MultiColorLED/MultiColorLED.h \
    ../../../modules/ghi/Potentiometer/Potentiometer.h \
    ../../../modules/ghi/PulseCount/PulseCount.h \
    ../../../modules/ghi/RelayX1/RelayX1.h \
    ../../../modules/ghi/RelayX16/RelayX16.h \
    ../../../modules/ghi/RotaryH1/RotaryH1.h \
    ../../../modules/ghi/RS232/RS232.h \
    ../../../modules/ghi/TemperatureHumidity/TemperatureHumidity.h \
    ../../../modules/ghi/Thermocouple/Thermocouple.h \
    ../../../modules/ghi/TouchC8/TouchC8.h \
    ../../../modules/ghi/TouchL12/TouchL12.h \
    ../../../modules/ghi/Tunes/Tunes.h \
    ../../../modules/ghi/USBSerial/USBSerial.h \
    ../../../modules/ghi/WiFiRN171/WiFiRN171.h \
    ../../../mainboards/ghi/FEZLynxS4/FEZLynxS4.h \
    ../../../mainboards/ghi/FEZLynxS4/include/FTDI_Device.h \
    ../../../ports/swig/proxy/core/System_proxy.hpp \
    ../../../ports/swig/proxy/core/Interfaces_proxy.hpp \
    ../../../modules/seeed/TemperatureHumidity/TemperatureHumidity.h \
    ../../../modules/seeed/Gyroscope/Gyroscope.hpp \
    ../../../modules/seeed/Compass/Compass.h \
    ../../../modules/seeed/Barometer/Barometer.h \
    ../../../modules/seeed/Accelerometer/Accelerometer.h

